name = "flipops-site"
pages_build_output_dir = ".vercel/output/static"
compatibility_date = "2024-09-14"
compatibility_flags = ["nodejs_compat"]

[vars]
NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY = "pk_test_dm9jYWwtY2F0ZmlzaC0yMi5jbGVyay5hY2NvdW50cy5kZXYk"
NEXT_PUBLIC_CLERK_SIGN_IN_URL = "/sign-in"
NEXT_PUBLIC_CLERK_SIGN_UP_URL = "/sign-up"
NEXT_PUBLIC_CLERK_AFTER_SIGN_IN_URL = "/app"
NEXT_PUBLIC_CLERK_AFTER_SIGN_UP_URL = "/app"
NEXT_PUBLIC_APP_URL = "https://flipops-site.pages.dev"